---
name: Tailscale no Host
version: dev
slug: tailscale-no-host
description: Zero config VPN for building secure networks (now without network:host!)
url: https://github.com/fritz3n/addon-tailscale-no-host
ingress: true
ingress_port: 0
ingress_stream: true
startup: services
panel_icon: mdi:vpn
arch:
  - aarch64
  - amd64
  - armv7
init: false
hassio_api: true
map:
  - share:rw
privileged:
 - NET_ADMIN
 - NET_RAW
schema:
  accept_dns: bool?
  accept_routes: bool?
  advertise_exit_node: bool?
  advertise_connector: bool?
  advertise_routes:
    - "match(^(((25[0-5]|(2[0-4]|1\\d|[1-9]?)\\d)\\.){3}(25[0-5]|(2[0-4]|1\\d|[1-9]?)\\d)\\/(3[0-2]|[12]?\\d)|[a-fA-F\\d.:]+:[a-fA-F\\d.:]+\\/(12[0-8]|(1[01]|[1-9]?)\\d))$)?"
  funnel: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  login_server: url?
  proxy: bool?
  proxy_and_funnel_port: match(^(443|8443|10000)$)?
  snat_subnet_routes: bool?
  stateful_filtering: bool?
  tags:
    - "match(^tag:[a-zA-Z][a-zA-Z0-9-]*$)?"
  taildrop: bool?
  userspace_networking: bool?
